const MAX_BINGO_NUMBERS = 90;
const LAST_BINGO_NUMBER = MAX_BINGO_NUMBERS - 1;
const GETTING_BARREL_NUMBER_TIME = 5;

export default {
  MAX_BINGO_NUMBERS,
  LAST_BINGO_NUMBER,
  GETTING_BARREL_NUMBER_TIME
};
